"""Add patient fields to medical records

Revision ID: d8aa00e88299
Revises: 
Create Date: 2026-04-06 15:51:05.401378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8aa00e88299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecords', sa.Column('patient_name', sa.String(length=255), nullable=True))
    op.add_column('medicalrecords', sa.Column('doctor_name', sa.String(length=255), nullable=True))
    op.add_column('medicalrecords', sa.Column('symptoms', sa.Text(), nullable=True))
    op.add_column('medicalrecords', sa.Column('visit_date', sa.String(), nullable=True))
    op.add_column('medicalrecords', sa.Column('created_by', sa.String(length=50), nullable=True))
    op.alter_column('medicalrecords', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('medicalrecords', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medicalrecords', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('medicalrecords', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('medicalrecords', 'created_by')
    op.drop_column('medicalrecords', 'visit_date')
    op.drop_column('medicalrecords', 'symptoms')
    op.drop_column('medicalrecords', 'doctor_name')
    op.drop_column('medicalrecords', 'patient_name')
    # ### end Alembic commands ###
